name: counter_riverpod
description: Counter app example with riverpod

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_riverpod: ^0.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
